function y= arduino_test(a, s_time, e_time, label)

letter_count= length(label);

for(j=1:letter_count)
    letter= label(j)
    if letter=='A'  %update the pin configuration according to the braille letters
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time)
    elseif letter=='B'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='C'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='D'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='E'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='F'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='G'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='H'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='I'
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        %             writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='J'
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        %             writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='K'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='L'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='M'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='N'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='O'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='P'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='Q'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='R'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='S'
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        %             writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='T'
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 0);
        pause(s_time);
        %             writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        %             writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='U'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 1);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='V'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 1);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='W'
        writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 1);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 1);
        pause(s_time);
        %             writeDigitalPin(a, 'D2', 0);
        writeDigitalPin(a, 'D3', 0);
        %             writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='X'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 1);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        %             writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='Y'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 1);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 1);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    elseif letter=='Z'
        writeDigitalPin(a, 'D2', 1);
        writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 1);
        writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 1);
        writeDigitalPin(a, 'D10', 1);
        pause(s_time);
        writeDigitalPin(a, 'D2', 0);
        %             writeDigitalPin(a, 'D3', 0);
        writeDigitalPin(a, 'D4', 0);
        %             writeDigitalPin(a, 'D7', 0);
        writeDigitalPin(a, 'D12', 0);
        writeDigitalPin(a, 'D10', 0);
        pause(e_time);
    end
end
y= 1;

end